services:
  db:
    image: postgres:16-alpine
    container_name: agencia_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: agencia
      POSTGRES_PASSWORD: agencia_dev_2026
      POSTGRES_DB: agencia_turismo
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
